### ISSUE TITLE
License for Commercial use

### ISSUE THREAD

**Issue by andys0975** [Ucas-HaoranWei/GOT-OCR2.0#20]
Would you release licence for commercial use?

**Comment by Paul21777** [comment]
The paper and the weights on hugging face are licensed under Apache2.0. I guess you can use it commercialy

**Comment by avsthiago** [comment]
Not sure, @Paul21777. The README says:

> Usage and License Notices: The data, code, and checkpoint are intended and licensed for research use only. They are also restricted to use that follow the license agreement of Vary.

**Comment by DillionLowry** [comment]
I'd also like to get some clarification on this, because if you ignore the snippet acsthiago posted it looks like you can use the model commercially, but you cannot use the datasets. This is how I'm interpreting it:

1. Code license (Apache 2.0): Applies to the source code of this repo
2. Data license (CC BY-NC 4.0): Applies to the datasets used to train the model
3. Pretrained model license (Apache 2.0): Applies to the actual model weights and architecture on HuggingFace
