### ISSUE TITLE
Suggestion： host checkpoint on huggingface & modelscope

### ISSUE THREAD

**Issue by ultranity** [Ucas-HaoranWei/GOT-OCR2.0#5]
Found this nice work for more general OCR scenerios, but for now it seems that the checkpoints are only hosted on google drive and 百度网盘? 

It will be more convenient to upload  your checkpoints to huggingface and modelscope(魔搭) for sharing and version control~

**Comment by NielsRogge** [comment]
Niels here from HF, happy to assist with an integration.

It looks like https://huggingface.co/docs/transformers/custom_models is best suited here (it might be that the authors already leveraged this since I see registering with custom code being done in the code base).

Found this paper from the paper page: https://huggingface.co/papers/2409.01704, would be great to make the models available on the hub along with dedicated tags like "ocr" and `pipeline_tag: image-to-text` in the README, so that people can find GOT more easily.

**Comment by Ucas-HaoranWei** [comment]
I will do this soon～

**Comment by ankitsomani** [comment]
Request you to do it please, since Google Drive has begun blocking the weights file due to too many downloads. 



> FileURLRetrievalError: Failed to retrieve file url:
> 
> 	Too many users have viewed or downloaded this file recently. Please
> 	try accessing the file again later. If the file you are trying to
> 	access is particularly large or is shared with many people, it may
> 	take up to 24 hours to be able to view or download the file. If you
> 	still can't access a file after 24 hours, contact your domain
> 	administrator.
>

**Comment by abhinand5** [comment]
Use this for the time being: https://huggingface.co/abhinand/GOT-OCR-2.0

Sample notebook:
https://colab.research.google.com/drive/1SDcHWnRScqUV0TigQgfGzz3XisdZs2Bm?usp=sharing

**Comment by Ucas-HaoranWei** [comment]
> Use this for the time being: https://huggingface.co/abhinand/GOT-OCR-2.0
> 
> Sample notebook: https://colab.research.google.com/drive/1SDcHWnRScqUV0TigQgfGzz3XisdZs2Bm?usp=sharing

Thanks for your support, but please close your huggingface link as we expect to release the official hugging face deployment tomorrow. Thank you for your support！

**Comment by Ucas-HaoranWei** [comment]
The official Huggingface codes can be found: https://huggingface.co/ucaslcl/GOT-OCR2_0
